### ISSUE TITLE
Pasting from Editor -> GMAIL results in poor formatting

### ISSUE THREAD

**Issue by amulyaparmar** [Darginec05/Yopta-Editor#12]
**Describe the bug**
When I copy paste data from the Editor to Gmail it results into poor formatting.

I do want to often paste items from editor from one client (particularly email clients) to another but I notice it is consistently poorly formatted.

Is there any way you can help?

<img width="579" alt="image" src="https://user-images.githubusercontent.com/35022914/216070666-27015af5-ed18-49f8-9bbe-454e72d88c07.png">

**To Reproduce**
1. Copy a few blocks from the editor
2. Paste into gmail new email
3. You should see weird blocks inside the email client

**Expected behavior**
There should ideally be no blocks inside the email 

**Screenshots**
Attached above

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Brave (chrome browser)

**Comment by Darginec05** [comment]
Hi mate 👋 
Thank you for reporting the issue!

It seems it's currently also copying the node settings buttons (plus button and drag button) from the editor.
Working on it

**Comment by Darginec05** [comment]
@amulyaparmar fixed in v1.1.3

**Comment by amulyaparmar** [comment]
Awesome thank you so much for tackling this so quickly!! Truly amazing project, idea and effort here. Grateful to have found it!
