### ISSUE TITLE
Error with Hyerlinks 

### ISSUE THREAD

**Issue by leasemagnets** [Darginec05/Yopta-Editor#18]
**Describe the bug**

**To Reproduce**
1. Add a hyperlink to a text that takes a full line
<img width="304" alt="image" src="https://user-images.githubusercontent.com/66034432/218290308-0974d114-95ed-4f1f-bdbd-e3bcf217029f.png">

2. Create a new line at the end of the line by pressing enter 
<img width="147" alt="image" src="https://user-images.githubusercontent.com/66034432/218290334-fc28685f-5226-41df-9279-ea0f871fdfd7.png">

3. ^ see the error with the "link" represented vertically in accurately

**Expected behavior**
There should be no link represented vertically.

**Desktop (please complete the following information):**
 - Browser: Brave

**Comment by Darginec05** [comment]
Thank you for reporting the issue!

Working on it.

**Comment by Darginec05** [comment]
It should be fixed in v1.1.4
