### ISSUE TITLE
Ability to select what features to show in the "insert block" menu

### ISSUE THREAD

**Issue by YolCruz** [Darginec05/Yopta-Editor#28]
**Is your feature request related to a problem? Please describe.**
Having all of the features in the insert block menu can be kind of overwhelming for certain users, and adding support for those kinds of blocks is hard for my backend

**Describe the solution you'd like**
To be able to pass a prop like an array of strings to select or exclude certain blocks from being present in the insert block menu

**Describe alternatives you've considered**
I guess I could try to hide the things I don't want with CSS selectors, but that feels like a hack

**Comment by Darginec05** [comment]
Hi @YolCruz!
Currently list of elements in Menu is static.
But in @v2 I will add this abillity, working on it.

So, example: 

```<SuggestionMenu>
<HeadingOne />
<HeadingTwo />
...other needed items
<SuggestionMenu/> ```

**Comment by Darginec05** [comment]
Here is an example of how it will solve your problem in the v2 :) 

https://github.com/Darginec05/Yopta-Editor/blob/yopta-editor%40v2/examples/pages/dev/index.tsx#L201

**Comment by Darginec05** [comment]
Stand by. 
[Version 2 is ready for release](https://github.com/Darginec05/Yopta-Editor/issues/48)

**Comment by Darginec05** [comment]
It's available now!
I prepared example for you - https://yopta-editor.vercel.app/examples/withNotionExample
