### ISSUE TITLE
Support for markdown state

### ISSUE THREAD

**Issue by maZahaca** [Darginec05/Yopta-Editor#34]
**Is your feature request related to a problem? Please describe.**
Currently we have a need to save results of the editor into markdown. So, later this markdown could be easily shown on the website or be restored back to the editor as its state.
I believe current json format is the most efficient way for saving, however it could be useful to have format for saving something more common in use - markdown / html. 

**Describe the solution you'd like**
Implement markdown support in v1 of the library 🙏 

**Other solutions**
DraftJS has a util helpers allowing to do export of state to/from HTML/Markdown

**Comment by the-watchmaker** [comment]
I need this too.

@Darginec05 Are you planning to support Markdown natively or in a plugin style?

**Comment by Darginec05** [comment]
@the-watchmaker I have plans to split it into separate package @yopta/exports in v2
So example of usage:
```
import { markdown, html } from '@yopta/exports'; 
markdown.serialize(<data>);
markdown.deserialize(<data>);
```

**Comment by Darginec05** [comment]
Stand by. 
[Version 2 is ready for release](https://github.com/Darginec05/Yopta-Editor/issues/48)

**Comment by Darginec05** [comment]
Hi @maZahaca @the-watchmaker!
Exports for html and markdown is available now! 

I prepared for you example - https://yopta-editor.vercel.app/examples/withExports
