### ISSUE TITLE
Important: NPM Package is missing / disappeared

### ISSUE THREAD

**Issue by amulyaparmar** [Darginec05/Yopta-Editor#51]
**Describe the bug**
I used to be able to find the yopta-editor package in npm, but for some reason its not being found. So when I try to npm install it doesn't work

**To Reproduce**
1. Go to 'npm.com', search for yopta-editor
2. And you will see no results are found.

**Comment by Darginec05** [comment]
It was moved to multipackage with name @yoopta
Check example - https://github.com/Darginec05/Yopta-Editor/blob/master/web/src/examples/withBasicExample.tsx
