### ISSUE TITLE
Custom styles not applied to Numbered List

### ISSUE THREAD

**Issue by ofgowtham** [Darginec05/Yopta-Editor#52]
**Describe the bug**
I tried to add custom styles to Numbered list, but its not been added. 

**To Reproduce**

`  NumberedList.extend({
    options: {
      HTMLAttributes: {
        spellCheck: false,
        className: 'numberedStyle',
      },
    },
  }),`

and style 
`
.numberedStyle {
  color: slateblue;
}`

**Expected behavior**
Should apple the styles

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows 11 22621.1702
 - Browser: Chrome 113.0.5672.93
 - Version :     "@stripe/react-stripe-js": "^2.1.0",
    "@stripe/stripe-js": "^1.52.1",
    "@yoopta/action-menu-list": "^1.9.3-rc",
    "@yoopta/blockquote": "^1.9.4-rc",
    "@yoopta/callout": "^1.9.3-rc",
    "@yoopta/code": "^1.9.3-rc",
    "@yoopta/editor": "1.9.5-rc",
    "@yoopta/embed": "^1.9.3-rc",
    "@yoopta/headings": "^1.9.3-rc",
    "@yoopta/image": "^1.9.3-rc",
    "@yoopta/link": "^1.9.3-rc",
    "@yoopta/lists": "^1.9.3-rc",
    "@yoopta/marks": "^1.9.3-rc",
    "@yoopta/paragraph": "^1.9.5-rc",
    "@yoopta/renderer": "^1.9.3-rc",
    "@yoopta/toolbar": "^1.9.3-rc",
    "@yoopta/video": "^1.9.3-rc",

**Comment by ofgowtham** [comment]
This is partially fixed in the latest version, the styles are initially applied, but when we create new numbered list or bulleted list, or while clicking the pre rendered list from the initial state, it goes back to default font.

**Comment by Darginec05** [comment]
Fixed in latest version
