### ISSUE TITLE
Need Hyperlink option in Marks/Toolbar

### ISSUE THREAD

**Issue by ofgowtham** [Darginec05/Yopta-Editor#54]
**Is your feature request related to a problem? Please describe.**
Need Hyperlink optior in the Toolbar

**Describe the solution you'd like**
Can able to select text and add hyperlink from Toolbar

**Describe alternatives you've considered**
Right now selecting the text and pasting (ctrl + v) the url does the trick. It would be easy for user to select if we have the option in the Toolbar itself

**Comment by Darginec05** [comment]
Added @yoopta/link-tool package  into default toolbar
