### ISSUE TITLE
I need function that validates JSON content for proper structure

### ISSUE THREAD

**Issue by Artmadiar** [Darginec05/Yopta-Editor#6]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I write content on backend, I'm scared that JSON has unpredictable structure.

**Describe the solution you'd like**
If you will implement it in package, it always be matched to its version.

Thanks!

**Comment by Darginec05** [comment]
Fixed. Now you can import this function directly from package
`import { isValidYoptaNodes } from 'yopta-editor'`
