### ISSUE TITLE
Broken links in v2 Readme

### ISSUE THREAD

**Issue by jifeon** [Darginec05/Yopta-Editor#60]
**Describe the bug**
Links in [this file](https://github.com/Darginec05/Yopta-Editor/blob/yopta-editor%40v2/README.md) are broken and lead to 404 pages.

![image](https://github.com/Darginec05/Yopta-Editor/assets/384223/983d0123-9977-44e1-abee-18c56abad8c4)

😢 

![image](https://github.com/Darginec05/Yopta-Editor/assets/384223/8fda4671-bb14-4989-af25-7d25109fd791)

**Comment by Darginec05** [comment]
Everything regarding the docs will be fixed within tomorrow
