### ISSUE TITLE
NPM unable to install

### ISSUE THREAD

**Issue by amulyaparmar** [Darginec05/Yopta-Editor#64]
**Describe the bug**
Hi Darcine, I know you mentioned that we could install the NPM package locally using the local scope name of @yoopta, but I wasn't able to do it. 

Is there a way/documented process for us to be able to install locally? And do you know what it will take to get it live on the NPM package library again?

**Comment by amulyaparmar** [comment]
@Darginec05 , thank you again for this package but I think I am very confused on how to install it without the yopta-editor package?

Are we supposed to clone the code and its components locally?

**Comment by Darginec05** [comment]
Hi @amulyaparmar!
Sorry for the late response, I was preparing release for v2.

In @v2 I turned to multipackages with @yoopta name. 
Check please examples: https://yopta-editor.vercel.app/examples/withBasicExample and source code
