### ISSUE TITLE
Remove unwanted padding from embedded link when rendered (read only) and make the embed editor responsive

### ISSUE THREAD

**Issue by ofgowtham** [Darginec05/Yopta-Editor#65]
Describe the bug

1. When editor is rendered with read only  <YooptaRenderer />, there's an unwanted padding under the embedded link and doesn't respect the custom/resized dimension set.
2. And the embed editor/resizer container should automatically resized to the embedded content while creating. For example if iframe content is small, there's space under it, if the content is big, it's overlapping the below block which should not happen.

```javascript
  Embed.extend({
    options: {
      maxWidth: 650,
      maxHeight: 500,
    },
  }),
``` 

To Reproduce

Add an embed link like Twitter, then render with and with out Yopta-renderer.

When i tried to add this link to the editor: [link1](https://twitter.com/warikoo/status/1672948002653360131) [link2](https://twitter.com/FabrizioRomano/status/1673599921260306432)

You can see both the issues with the below video:

https://github.com/Darginec05/Yopta-Editor/assets/24489435/eaccc592-333b-4eca-99c2-086a9ca890cc

Expected behavior
There should not be extra padding and respect the resized dimension.
The editor/resizer should be responsive to embedded link's dimension.

Screenshots

Desktop (please complete the following information):

OS: Windows 11 22621.1702
Browser: Chrome 113.0.5672.93
Version : 
 "@yoopta/action-menu-list": "^1.9.10-rc",
    "@yoopta/callout": "^1.9.10-rc",
    "@yoopta/code": "^1.9.10-rc",
    "@yoopta/editor": "1.9.14-rc",
    "@yoopta/embed": "^1.9.10-rc",
    "@yoopta/headings": "^1.9.10-rc",
    "@yoopta/image": "^1.9.10-rc",
    "@yoopta/link": "^1.9.10-rc",
    "@yoopta/link-tool": "^1.9.3-rc",
    "@yoopta/lists": "^1.9.10-rc",
    "@yoopta/marks": "^1.9.10-rc",
    "@yoopta/paragraph": "^1.9.12-rc",
    "@yoopta/renderer": "^1.9.10-rc",
    "@yoopta/toolbar": "^1.9.10-rc",
    "@yoopta/video": "^1.9.10-rc",

**Comment by Darginec05** [comment]
Fixed in latest version "@yoopta/embed": "^1.9.18-rc"
