### ISSUE TITLE
Add embed support for LinkedIn and Reddit

### ISSUE THREAD

**Issue by ofgowtham** [Darginec05/Yopta-Editor#66]
**Is your feature request related to a problem? Please describe.**
Add embed support for LinkedIn and Reddit

**Describe alternatives you've considered**
using src link from Linkedin is working for now but direct url link support needed

```
<iframe src="https://www.linkedin.com/embed/feed/update/urn:li:share:7079089495559589888" height="575" width="504" frameborder="0" allowfullscreen="" title="Embedded post"></iframe>
``` 

Reddit using blockquote so its not working too.

**Additional context**
when trying to add direct reddit or linkedin link

![Screenshot (86)](https://github.com/Darginec05/Yopta-Editor/assets/24489435/22ff7d32-e881-47a1-a5d0-817302e457b9)

![Screenshot (85)](https://github.com/Darginec05/Yopta-Editor/assets/24489435/c0124f51-b9f8-4930-999f-c0181094c80b)

**Comment by Darginec05** [comment]
Fixed in latest version of `"@yoopta/embed": "^1.9.18-rc"`
Check in examples with this embed link: 

https://embed.reddit.com/r/reactjs/comments/15mkqew/open_source_editor_yoopta_testing_before_release
