### ISSUE TITLE
Change Youtube Embed Thumbnail language to English

### ISSUE THREAD

**Issue by ofgowtham** [Darginec05/Yopta-Editor#67]
Describe the bug

The embedded Youtube Thumbnail is in some other language, it needs to be in English

To Reproduce

Add a Youtube link

![Screenshot 2023-06-28 231617](https://github.com/Darginec05/Yopta-Editor/assets/24489435/d2b7d3c5-5ce7-41c5-815f-b49e8a9e7de2)

Expected behavior
It should be in english. 
I've checked the code at "packages\yoopta-embed\src\providers\YoutubePlayer.tsx"
```
            <iframe
              title="Youtube Player"
              // https://developers.google.com/youtube/player_parameters?hl=en
              src={`https://www.youtube.com/embed/${providerId}?hl=no&rel=0`}
              frameBorder={0}
              onLoad={() => setFrameLoaded(true)}
              allowFullScreen
              className={s.iframe}
              {...other}
            />
``` 

changing  hl=no to hl=en might solve the issue like below

```
`https://www.youtube.com/embed/${providerId}?hl=en&rel=0`
``` 

Screenshots

Desktop (please complete the following information):

OS: Windows 11 22621.1702
Browser: Chrome 113.0.5672.93
Version : 
   "@yoopta/action-menu-list": "^1.9.10-rc",
    "@yoopta/callout": "^1.9.10-rc",
    "@yoopta/code": "^1.9.10-rc",
    "@yoopta/editor": "1.9.14-rc",
    "@yoopta/embed": "^1.9.10-rc",
    "@yoopta/headings": "^1.9.10-rc",
    "@yoopta/image": "^1.9.10-rc",
    "@yoopta/link": "^1.9.10-rc",
    "@yoopta/link-tool": "^1.9.3-rc",
    "@yoopta/lists": "^1.9.10-rc",
    "@yoopta/marks": "^1.9.10-rc",
    "@yoopta/paragraph": "^1.9.12-rc",
    "@yoopta/renderer": "^1.9.10-rc",
    "@yoopta/toolbar": "^1.9.10-rc",
    "@yoopta/video": "^1.9.10-rc",

**Comment by Darginec05** [comment]
Fixed in: 
@yoopta/video-1.9.12-rc
@yoopta/embed-1.9.12-rc
