### ISSUE TITLE
Progress bar on video uploading

### ISSUE THREAD

**Issue by Artmadiar** [Darginec05/Yopta-Editor#7]
**Is your feature request related to a problem? Please describe.**
I upload huge videos and it's kind of frustrating to not understand how many percentage left
Is there some way to pass function on "changing" / uploading video to update current state of uploading?

**Describe the solution you'd like**
```
<YoptaEditor
  value={value}
  onChange={onChange}
  media={
    videoProps: {
      onChange: (file: File, onUploadProgress: () => void) => onChangeMedia(file, 'video', onUploadProgress),
    },
  }
/>
```

**Comment by Darginec05** [comment]
You can provide custom loader for media props.
For example:

`<YoptaEditor
  value={value}
  onChange={onChange}
  media={
    videoProps: {
      onChange: (file: File, onUploadProgress: () => void) => onChangeMedia(file, 'video', onUploadProgress),
      loader: <MyLoader />
    },
  }
/>`
