### ISSUE TITLE
Drag'n'drop of headers

### ISSUE THREAD

**Issue by Artmadiar** [Darginec05/Yopta-Editor#8]
**Describe the bug**
I had a page with following content:
embed
embed
h1

I could move embed down, but not the header up.

**To Reproduce**
1. Add embed
2. Add header 1
3. Try to move header in the beginning of the page

 - MacOS 12.6.1 (21G217) Monterey
 - Browser Chrome Version 108.0.5359.124 (Official Build) (x86_64)
 - Version 1.0.23

**Comment by Darginec05** [comment]
Thanks for report!
This bug fixed in v1.0.31
