### ISSUE TITLE
Where is installation instructions? 

### ISSUE THREAD

**Issue by devprodct** [Darginec05/Yopta-Editor#89]
Maybe I lost something, but I can't get it.

**Comment by Darginec05** [comment]
I'll add it today

**Comment by devprodct** [comment]
Thanks :)

**Comment by rahulsai1999** [comment]
Hi @Darginec05, this is an excellent library. Could you please post the installation instructions? I have been having build errors on my Next.js project when I tried to install. Thanks.

**Comment by Darginec05** [comment]
@devprodct sorry that it took longer :) 
Here is instructions - https://github.com/Darginec05/Yopta-Editor#getting-started

**Comment by Darginec05** [comment]
@rahulsai1999 Hi, thanks for your feedback ˆ-ˆ
I have added getting started instructions - https://github.com/Darginec05/Yopta-Editor#getting-started.

Please let me know if you have any questions
