### ISSUE TITLE
Custom node element for my iframe video

### ISSUE THREAD

**Issue by Artmadiar** [Darginec05/Yopta-Editor#9]
**Is your feature request related to a problem? Please describe.**
I upload videos to bunny.net hosting with API and videos must be rendered with bunny.net iframe due its security reasons (videos are private).
Can you give me interface to pass my own custom node element please?
How can I override render function of "video" node element?

**Comment by Darginec05** [comment]
Hello, @Artmadiar! Thanks for the report.
I have plans to add the ability in `v2` to create custom `renders` and `editor` for each element
