### ISSUE TITLE
Copy and pasting from external source to Yopta Editor adds unwanted new lines in Firefox browser

### ISSUE THREAD

**Issue by ofgowtham** [Darginec05/Yopta-Editor#94]
**Describe the bug**

1. Copy and pasting from external source to Yopta Editor adds unwanted new lines in Firefox browser
2. Pasing paragraphs that contains hyperlinks to Yopta Editor turns into single hyperlink text

**To Reproduce**
1. Copy from any article, for example [link](https://getpocket.com/explore/item/an-evolutionary-timeline-of-homo-sapiens?utm_source=pocket-newtab-en-intl)
3. Paste it in the Yopta Editor

**Expected behavior**

1. The unwanted newlines should not be added after pasting.
2. Enitre copied paragraphs should be added properly with hyperlinks.

**Screenshots**

https://github.com/Darginec05/Yopta-Editor/assets/24489435/e6f5ca62-ee5b-4bdb-9d3b-362c4103f6b9

https://github.com/Darginec05/Yopta-Editor/assets/24489435/128174b9-8ed6-41d8-a9af-a5d25f3b26ca

Desktop (please complete the following information):

OS: Windows 11 22621.1702
Browsers: Chrome 113.0.5672.93
Firefox 118.0.1 (64-bit)

Version :
"@stripe/stripe-js": "^1.52.1",
"@yoopta/action-menu-list": "^1.9.5-rc",
"@yoopta/blockquote": "^1.9.6-rc",
"@yoopta/callout": "^1.9.5-rc",
"@yoopta/code": "^1.9.5-rc",
"@yoopta/editor": "1.9.9-rc",
"@yoopta/embed": "^1.9.5-rc",
"@yoopta/headings": "^1.9.5-rc",
"@yoopta/image": "^1.9.5-rc",
"@yoopta/link": "^1.9.5-rc",
"@yoopta/lists": "^1.9.5-rc",
"@yoopta/marks": "^1.9.5-rc",
"@yoopta/paragraph": "^1.9.7-rc",
"@yoopta/renderer": "^1.9.5-rc",
"@yoopta/toolbar": "^1.9.5-rc",
"@yoopta/video": "^1.9.5-rc",

**Comment by Darginec05** [comment]
Fixed in @yoopta/editor@1.9.26-rc
