### ISSUE TITLE
Issue with installing plugins

### ISSUE THREAD

**Issue by pushpa1105** [Darginec05/Yopta-Editor#99]
**Describe the bug**
 - There seems to be an issue with installing plugins. I get error like this. 
![image](https://github.com/Darginec05/Yopta-Editor/assets/96721462/ba1678ed-6961-43fa-8606-990d76cfee4c)

But it will work if I do `--force` install

**To Reproduce**
1. Setup nextjs project
2. After that follow instruction provided in installation guide([here](https://github.com/Darginec05/Yopta-Editor#getting-started)).
3. Then try to install other yoopta plugins.

**package version**
```
    "next": "13.4.12",
    "react": "18.2.0",
```

**Comment by Darginec05** [comment]
That's strange, it works for me.
Do you use /pages or /app route?

**Comment by Darginec05** [comment]
Send me please your `package.json` and code how you use `YooptaEditor` component

**Comment by pushpa1105** [comment]
@Darginec05 
I tried with next 14 too. I have still getting this error.

Here is the repo:
https://github.com/pushpa1105/yoopta-editor-bug.git

After setup, just try `npm install @yoopta/blockquote`

I am using node `v18.17.1` and npm `9.6.7`.

I am using POP OS(22.04 LTS).

**Comment by Darginec05** [comment]
Found issue, it seems problems only with `@yoopta/blockquote`
